#!/usr/bin/env python3
"""Generate go/cmd/sobs/route_allow_gen.go from the introspected Werkzeug route map.

The Go router (net/http ServeMux) registers handlers by path only, so a request with a
method the route does not allow reaches the handler instead of getting Werkzeug's 405. This
emits, for every EXACT (non-parameterized) route, the alphabetically-sorted `Allow` header
Werkzeug produces — declared methods plus auto-HEAD (where GET is allowed) plus the
always-present OPTIONS. route_guard.go turns that table into a registration-time method guard.

Parameterized routes (`has_params`) are skipped: in Go they are served by prefix sub-routers
that do their own per-subpath method dispatch, so a single path->methods entry cannot describe
them. The guard leaves those untouched.

Source of truth: migration/manifest/routes.generated.json (the live Werkzeug URL map captured
by extract_routes_runtime.py). Regenerate after any route change:

    python3 migration/tools/gen_route_methods.py
    gofmt -w go/cmd/sobs/route_allow_gen.go   # this emits single-space output; gofmt aligns it
"""

from __future__ import annotations

import collections
import json
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
REPO = TOOLS.parent.parent
GEN = REPO / "migration" / "manifest" / "routes.generated.json"
OUT = REPO / "go" / "cmd" / "sobs" / "route_allow_gen.go"


def build() -> dict[str, str]:
    routes = json.loads(GEN.read_text())["routes"]
    by_path: dict[str, set[str]] = collections.defaultdict(set)
    for r in routes:
        if r.get("has_params"):
            continue  # served by a Go prefix sub-router; not an exact-match guard target
        by_path[r["path"]].update(r["methods"])
    allow: dict[str, str] = {}
    for path, methods in by_path.items():
        m = set(methods)
        if "GET" in m:
            m.add("HEAD")  # Werkzeug auto-provides HEAD wherever GET is allowed
        m.add("OPTIONS")  # ...and OPTIONS on every rule (provide_automatic_options)
        allow[path] = ", ".join(sorted(m))  # Werkzeug sorts the Allow method set
    return allow


def render(allow: dict[str, str]) -> str:
    lines = [
        "package main",
        "",
        "// Code generated by migration/tools/gen_route_methods.py. DO NOT EDIT.",
        "//",
        "// rawRouteAllow maps each exact (non-parameterized) Werkzeug route path to the",
        "// alphabetically-sorted Allow header value Werkzeug emits — declared methods plus",
        "// auto-HEAD (where GET is allowed) plus the always-present OPTIONS. route_guard.go",
        "// expands each into a membership set and a registration-time 405/OPTIONS guard.",
        "var rawRouteAllow = map[string]string{",
    ]
    for path in sorted(allow):
        lines.append(f"\t{go_quote(path)}: {go_quote(allow[path])},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def go_quote(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    allow = build()
    OUT.write_text(render(allow))
    print(f"wrote {OUT.relative_to(REPO)} with {len(allow)} exact routes")


if __name__ == "__main__":
    main()
